---
# Per environment values which override defaults in hmpps-integration-api/values.yaml

generic-service:
  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    SENTRY_ENV: pre-production

  namespace_secrets:
    client-credentials:
      CLIENT_ID: "clientId"
      CLIENT_SECRET: "clientSecret"

  ingress:
    host: hmpps-integration-api-pre-production.apps.live.cloud-platform.service.justice.gov.uk
    annotations:
      nginx.ingress.kubernetes.io/auth-tls-secret: "hmpps-integration-api-pre-production/client-certificate"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
