---
# Per environment values which override defaults in hmpps-integration-api/values.yaml

generic-service:
  replicaCount: 2

  image:
    repository: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/hmpps-integration-api-admin-team/hmpps-integration-api-pre-production-ecr

  ingress:
    host: hmpps-integration-api-pre-production.apps.live.cloud-platform.service.justice.gov.uk
    annotations:
      nginx.ingress.kubernetes.io/auth-tls-secret: "hmpps-integration-api-pre-production/api-gateway-client-certificate"

  env:
    SPRING_PROFILES_ACTIVE: pre-production
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    SENTRY_ENV: pre-production

  namespace_secrets:
    client-credentials:
      CLIENT_ID: "clientId"
      CLIENT_SECRET: "clientSecret"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
