name: Generate code documentation

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  generate-docs:
    if: github.actor != 'dependabot[bot]'
    name: ðŸ§¹ Generate code docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Generate code docs
        run: ./gradlew codeDoc
