name: Generate code documentation

on:
  push:
    branches:
      - 'HIA-1079_code_doc_poc'

jobs:
  generate-docs:
    if: github.actor != 'dependabot[bot]'
    name: ðŸ§¹ Generate code docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
      - uses: gradle/actions/setup-gradle@v5
      - name: Generate code docs
        run: ./gradlew codeDoc
