name: Generate PlantUML Diagrams and Config

on:
  - workflow_dispatch
  - push

jobs:
  generate:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs/diagrams
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
    steps:
      - uses: actions/checkout@v6
      - name: Install Graphviz Dependency
        run: |
          sudo apt-get install graphviz
      - name: Install PlantUML
        run: |
          wget https://github.com/plantuml/plantuml/releases/download/v1.2025.2/plantuml.jar
          java -jar plantuml.jar -version
      - name: Generate Diagrams
        run: |
          java -jar plantuml.jar -svg *.puml
      - name: Setup Git Config
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Commit images
        run: |
          git add *.svg
          git commit -m "Exported .PUML PlantUML diagrams to .SVG" || true
          git push origin ${BRANCH_NAME}
      - uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
      - uses: gradle/actions/setup-gradle@v5
      - name: Check Subscription Policies
        run: |
          cd ../../
          ./gradlew generateFilterPolicies
      - name: Commit changes
        run: |
          git add ../../src/main/resources/event-filter-policies/.
          git commit -m "Subscription filter policy changes" || true
          git push origin ${BRANCH_NAME}
