# Need a GitHub Advanced Security license to run this action on private repos.

name: Review dependency changes
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

permissions:
  contents: read

jobs:
  review-dependency-changes:
    name: üïµÔ∏è Review dependency changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Review dependency changes
        uses: actions/dependency-review-action@v3
        with:
          # Possible values: critical, high, moderate, low
          fail-on-severity: critical
